version: '3.8'

networks:
  demo:

services:
  load_balancer:
      image: nginx
      container_name: load_balancer
      networks:
        - demo
      ports:
        - "5000:80"
      depends_on:
        - graphkeeper_1
        - graphkeeper_2
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      extra_hosts:
        - "host.docker.internal:host-gateway"

  graphkeeper_1:
      image: margostino/graphkeeper:1.0.0-SNAPSHOT
      container_name: graphkeeper_1
      environment:
        - QUARKUS_PROFILE=docker
      networks:
        - demo
      ports:
        - "5001:8080"
      healthcheck:
        test: ["CMD", "curl", "localhost:8080/ping | grep UP || exit 1"]
        interval: 15s
        timeout: 5s
        retries: 20
        start_period: 10s
      extra_hosts:
        - "host.docker.internal:host-gateway"

  graphkeeper_2:
      image: margostino/graphkeeper:1.0.0-SNAPSHOT
      container_name: graphkeeper_2
      environment:
        - QUARKUS_PROFILE=docker
        - HAZELCAST_IP_MEMBERS=$(awk 'END{print $1}' /etc/hosts)
      networks:
        - demo
      ports:
        - "5002:8080"
      healthcheck:
        test: ["CMD", "curl", "localhost:8080/ping | grep UP || exit 1"]
        interval: 15s
        timeout: 5s
        retries: 20
        start_period: 10s
      extra_hosts:
        - "host.docker.internal:host-gateway"

  hazelcast_manager:
    image: hazelcast/management-center
    container_name: hazelcast_manager
    networks:
        - demo
    depends_on:
      - graphkeeper_1
      - graphkeeper_2
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
        - ./docker/hazelcast/cluster.yml:/opt/hazelcast/cluster.yml
#     command: "/opt/hazelcast/management-center/bin/hz-mc conf cluster add -cn=dev -ma=graphkeeper_1"
#     command: "/opt/hazelcast/management-center/bin/hz-mc conf cluster add --client-config=/opt/hazelcast/cluster.yml -v"
    environment:
      - JAVA_OPTS=-Dhazelcast.mc.healthCheck.enable=true --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
#       - MC_INIT_CMD=/opt/hazelcast/mancenter/mc-conf.sh create-user -H=/data -n=gk -p=ampx2020 -r=admin -v

#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./docker/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
#      - ./docker/grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
#      - ./docker/grafana/dashboards/demo.json:/etc/grafana/provisioning/dashboards/demo.json
  #      - ./docker/grafana/dashboards/create_session.json:/etc/grafana/provisioning/dashboards/create_session.json
  #      - ./docker/grafana/dashboards/drop_session.json:/etc/grafana/provisioning/dashboards/drop_session.json

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'

#  hazelcast-mgmt:
#    image: hazelcast/management-center:3.12.8
#    ports:
#      - "8080:8080"
#      - "8081:8081"
#    environment:
#      - JAVA_OPTS=-Dhazelcast.mc.healthCheck.enable=true --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
#      - MC_INIT_CMD=/opt/hazelcast/mancenter/mc-conf.sh create-user -H=/data -n=amplifix -p=ampx2020 -r=admin -v

#  load-balancer:
#    image: nginx
#    ports:
#      - "5000:80"
#    volumes:
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf