openapi: 3.0.3
info:
  title: GraphKeeper
  description: GraphKeeper specificacion to support CRUD operation in runtime over the GraphQL Schema and Data Fetcher configuration
  version: 1.0.0
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: graphql
    description: GraphQL configuration change on runtime
servers:
  - url: 'https://graphkeeper.org'
paths:
  /data_fetchers:
    post:
      tags:
        - graphql
      summary: Add a new data fetcher
      description: ''
      operationId: addDataFetcher
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataFetcher'
        '405':
          description: Invalid input
      security:
        - gk_api_key: [ ]
      requestBody:
        $ref: '#/components/requestBodies/DataFetcher'

components:
  requestBodies:
    DataFetcher:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataFetcher'
      description: Data Fetcher object that needs to be added to the configuration
      required: true
  securitySchemes:
    gk_api_key:
      type: apiKey
      name: gk_api_key
      in: header
  schemas:
    DataFetcher:
      title: Data Fetcher
      description: A data fetcher for a given GraphQL type and field
      type: object
      properties:
        id:
          type: string
          example: data_fetcher_1
        connector_type:
          type: string
          enum:
            - http
        description:
          type: string
        endpoint:
          type: string
          pattern: '^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$'
        username:
          type: string
        password:
          type: string
    ApiResponse:
      title: An uploaded response
      description: Describes the result of uploading an image resource
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  
